# Here you can change the language of this module.
# Currently, the following languages are available:
#
#  'en' -> English translations.
#  'de' -> German translations.
module-language: en
# Here you can change the database sync time in seconds.
# This is the time in seconds when the plugin will synchronize the database with the server.
# Do not set this value too low, as it can cause performance issues.
# The default value is 120 seconds.
database-sync-time: 120
# Here you can change some settings related to the default currency.
default-currency:
  # Start Balance if the player comes new to the server.
  start-balance: 200.00
  # Printing a first join message to the new Player in Chat.
  enable-first-join-message: true
  # currency via plural
  currency-name-plural: 'EURs'
  # currency via singular
  currency-name-singular: 'EUR'
  # This is the amount of fractional digits shown in any messages and lore's.
  # Set it to 0 if you don't want to show no fractional digits.
  fractional-digits: 2
  # The max possible money amount. If a player reaches this value, he can't get any more money.
  # LightEconomy can process a maximum of:
  # - max-pocket-balance: 1.7976931348623157E308
  # This is the maximum number you can use.
  max-pocket-balance: 100000000000000000000
# Here you can change the settings for the Title Animation.
# The Title Animation will be shown when a player receives or lose money.
# The Animations will trigger by the following events:
# — Player receives money. (e.g., any income or payment from third party plugins).
# — Player loses money. (e.g., any expenses or payment to third party plugins).
# — Any LightEconomy add or remove money commands.
# The translation of the Title Animation is in the current used language file.
title-animation:
  # Enable or disable the Title Animation.
  enable: true
  # The Title Animation will only be shown if the target value is greater or equal than this value.
  min: 15000
  # The style of the Title Animation.
  # style: LINEAR – The title will count linear from 0 to the target value.
  # style: EXPONENTIAL – The title will count exponential from 0 to the target value. (not implemented yet)
  style: LINEAR
  # The duration of the Title Animation in seconds.
  duration: 4
  sound-settings:
    # Enable or disable the sound of the Title Animation.
    enable: true
    # The sound of the Title Animation.
    # The sound will only be played if the target value is greater or equal than this value.
    sound: BLOCK_NOTE_BLOCK_PLING
    # The volume of the sound.
    volume: 1.0
    # The sound channel where the sound will be played.
    channel: GLOBAL
# Here you can change the settings for the Top List.
# The translations are in the current used language file.
# en.yml -> topCommand -> header 'Top 10 Players with the largest balance on the server'
# en.yml -> topCommand -> entry 'Top 10 Players with the largest balance on the server'
# en.yml -> topCommand -> footer 'Top 10 Players with the largest balance on the server'
hologram-settings:
  amount: 10
# Here you can change all the main settings related to the eco module.
main-settings:
  # The amount of players shown in the Top List Command
  baltop-amount: 10
  date-format: 'dd:MM:yyyy'