name: lightEco
author: lightStudio
version: 0.1.0
main: io.lightstudio.economy.Light
api-version: 1.13
depend: ["PlaceholderAPI", "Vault"]
softdepend: ["Towny"]
loadbefore: [CoinsEngine, EssentialsX, Towny]
libraries: []
#  - org.mariadb.jdbc:mariadb-java-client:2.7.4
#  - com.zaxxer:HikariCP:5.1.0
commands:
  lighteco:
    description: The root command for LightEco overall
    aliases: [le, leco, lighteconomy]
  bal:
    description: The root command for LightEco overall
    aliases: [money, eco, economy, balance]
  pay:
    description: send money to another player
    aliases: [payment]